Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11"
    config.vm.box_check_update = false
    config.vm.define "serverlinux" do |serverlinux|
      serverlinux.vm.provider "virtualbox" do |vb|
        vb.name = "serverlinux"
        vb.memory = 4096
        vb.cpus = 2
      end
      serverlinux.vm.hostname = "serverlinux"
#      serverlinux.vm.network "private_network", ip: "192.168.150.10"
      serverlinux.vm.provision "shell", path: "./setup.sh" do |s|
        s.args = ["serverlinux"]
      end
    end 
end
