Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11"
    config.vm.box_check_update = false
    config.vm.define "linux_v1" do |linux_v1|
      linux_v1.vm.provider "virtualbox" do |vb|
        vb.name = "linux_v1"
        vb.memory = 4096
        vb.cpus = 2
      end
      linux_v1.vm.hostname = "linux_v1"
      linux_v1.vm.provision "shell", path: "./setup.sh" do |s|
        s.args = ["linux_v1"]
      end
    end 
end
